In [6]:
import numpy as np
import matplotlib.pyplot as pl
import pandas as pd

In [7]:
dat=pd.read_csv('winequality-red.csv')
x=dat.iloc[:,:-1].values
y=dat.iloc[:,-1].values

In [8]:
print(x)

[[ 7.4    0.7    0.    ...  3.51   0.56   9.4  ]
 [ 7.8    0.88   0.    ...  3.2    0.68   9.8  ]
 [ 7.8    0.76   0.04  ...  3.26   0.65   9.8  ]
 ...
 [ 6.3    0.51   0.13  ...  3.42   0.75  11.   ]
 [ 5.9    0.645  0.12  ...  3.57   0.71  10.2  ]
 [ 6.     0.31   0.47  ...  3.39   0.66  11.   ]]


In [9]:
print(y)

[5 5 5 ... 6 5 6]


In [10]:
dat

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [15]:
dat.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [17]:
from sklearn.model_selection import train_test_split as tts
xtrn,xtst,ytrn,ytst= tts(x,y,test_size=0.2)
print(xtrn,"X-train\n\n",xtst,"X-test\n\n",ytrn,"Y-train\n\n",ytst,"Y-test\n\n")

[[6.80e+00 4.80e-01 2.50e-01 ... 3.34e+00 6.00e-01 1.04e+01]
 [7.30e+00 3.50e-01 2.40e-01 ... 3.43e+00 5.40e-01 1.00e+01]
 [8.00e+00 7.10e-01 0.00e+00 ... 3.44e+00 5.30e-01 9.50e+00]
 ...
 [6.10e+00 5.90e-01 1.00e-02 ... 3.52e+00 5.60e-01 1.14e+01]
 [8.00e+00 4.20e-01 1.70e-01 ... 3.29e+00 6.10e-01 9.20e+00]
 [1.06e+01 4.20e-01 4.80e-01 ... 3.21e+00 8.70e-01 1.13e+01]] X-train

 [[ 7.5   0.51  0.02 ...  3.36  0.54 10.5 ]
 [ 8.9   0.24  0.39 ...  3.12  0.59  9.5 ]
 [ 8.    0.64  0.22 ...  3.37  0.58 11.  ]
 ...
 [12.3   0.27  0.49 ...  3.2   0.8  10.2 ]
 [ 7.2   1.    0.   ...  3.43  0.46 10.  ]
 [ 6.8   0.36  0.32 ...  3.36  0.55 12.8 ]] X-test

 [5 4 5 ... 5 6 6] Y-train

 [6 6 5 5 8 4 5 5 6 5 6 6 6 6 5 5 7 6 5 6 5 5 5 7 6 6 6 6 5 6 5 5 5 6 5 4 5
 5 6 5 5 7 6 5 6 6 6 6 7 4 6 5 5 5 5 6 6 5 5 5 5 6 6 7 6 5 5 5 5 5 5 7 5 4
 6 7 5 5 5 6 4 6 6 6 7 6 6 5 5 6 5 5 5 7 5 5 5 4 8 5 6 6 5 6 6 5 7 5 5 5 5
 6 5 7 7 7 5 5 5 5 6 5 6 6 5 6 5 6 5 6 7 7 6 6 6 5 5 6 6 5 4 6 5 5 5 7 7 5
 5 5 5 5 7 5 5 5 